default: main

main.o:
	g++ -c main.cpp

account.o: account.cpp
	g++ -c main account.cpp account.h

checking.o: checking.cpp
	g++ -c main checking.cpp checking.h

savings.o: savings.cpp
	g++ -c main savings.cpp saving.h

creditcard.o: creditcard.cpp
	g++ -c main creditcard.cpp creditcard.h

clean:
	rm -f main.o main
